language: node_js
node_js:
  - 'lts/*'
cache: yarn
install:
  - yarn install
script:
  - yarn test
  - yarn build
before_deploy:
  - cd dist
deploy:
  provider: npm
  cleanup: false
  email: '$NPM_EMAIL'
  api_token: '$NPM_TOKEN'
  on:
    tags: true
